### ISSUE TITLE
use-client-interface

### ISSUE THREAD

**Issue by adsamu** [LiU-SeeGoals/controller#55]
Currently ai.go uses client.GrsimClient to send stuff but it should use the interface client.Client so its indifferent to wether its sending commands to real robots or a simulation. It should work just changing it in the Ai struct but an InvalidIfaceAssign error is raised. 

repo: controller
Location: internal/ai/ai.go, internal/client/*

Fix this.

**Comment by jakob321** [comment]
changed all the grsim proto to simulation
