### ISSUE TITLE
update how the velocity calculation works

### ISSUE THREAD

**Issue by jakob321** [LiU-SeeGoals/controller#66]
Currently in robot.go the velocity is calculated by comparing to previous position. However, when using cameras, the robots jitter a bit, therefor making the velocity calculations faulty. 

Ideas on how to update:
1. Compare to position further back in time?
2. Compare to previous velocity and create a moving average?

**Comment by adsamu** [comment]
The velocity calculations also should probably be moved out of the gamestate package and into worldpredictor as that makes more sense

**Comment by Arty-Facts** [comment]
The velocity estimation has been moved back into the gamestate :P

**Comment by jakob321** [comment]
very nice
