### ISSUE TITLE
add ssl-game-controller to the docker stack

### ISSUE THREAD

**Issue by adsamu** [LiU-SeeGoals/controller#67]
Add the [ssl-game-controller](https://github.com/RoboCup-SSL/ssl-game-controller) to the docker stack, this should be trivial.

Then a client should be initialized somewhere in [controller](https://github.com/LiU-SeeGoals/controller/) that subscribes to the the multicast. This should probably be in the ai package.

**Comment by jakob321** [comment]
very nice
