### ISSUE TITLE
Python slow brain

### ISSUE THREAD

**Issue by david-bergstrom** [LiU-SeeGoals/controller#93]
Related to https://github.com/LiU-SeeGoals/seegoals/issues/1

**Comment by david-bergstrom** [comment]
Main idea is to start simple and work from there. Python side hosts a small HTTP-server which can receive the game state in a POST message. This state can then be processed into a high-level objective on Python-side.  The high-level plan is included in the return message, which always returns the latest plan if available.

**Comment by Arty-Facts** [comment]
this is done
